[phases.setup]
nixPkgs = [
  'chromium',
  'nss',
  'freetype',
  'harfbuzz',
  'ca-certificates',
  'fontconfig',
  'liberation_ttf',
]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/run/current-system/sw/bin/chromium"
